version: '3.5'

services:

  jaeger-agent:
    container_name: jaeger_agent
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/tcp"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - LOG_LEVEL=debug
    networks:
      - profiling

  booking:
    image: epam/contexts:booking-latest
    container_name: booking
    build:
      context: ./booking
      dockerfile: Dockerfile
    ports:
      - "8383:8383"
      - "1313:1313"
    environment:
      JAVA_OPTS: '-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1313 -Xms64m -Xmx512m'
      JAEGER_SERVICE_NAME: booking
      JAEGER_AGENT_HOST: jaeger-agent
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    links:
      - auditor
    depends_on:
      - auditor
      - jaeger-agent
    networks:
      - profiling

  auditor:
    image: epam/contexts:auditor-latest
    container_name: auditor
    build:
      context: ./auditor
      dockerfile: Dockerfile
    ports:
      - "8384:8384"
      - "1314:1314"
    environment:
      JAVA_OPTS: '-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1314 -Xms64m -Xmx512m'
      JAEGER_SERVICE_NAME: booking
      JAEGER_AGENT_HOST: jaeger-agent
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    depends_on:
      - jaeger-agent
    networks:
      - profiling

volumes:
  vol_postgres:

networks:
  profiling:
    driver: bridge