server:
  port: 8383

spring:
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

auditor:
  url: http://auditor:8384
  accept-booking-uri: /api/v1/booking/accept